import type { Metadata } from 'next'
import './globals.css'
import { ThemeContextProvider } from '@/providers/ThemeContext'
import ThemeProvider from '@/providers/ThemeProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
